apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: mu6f1av1g-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:a900a2630c6b23abb001b2ba9bbfc10dc2b04057@sha256:9839c0f7c4c19e3acb9c30956225bfeaa5624ff563077a3456d433612e47ec5c
          name: container-image
